services:
  mysql:
    image: mysql:8.4.0
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - db/init.sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql_secret
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_secret
      MYSQL_DATABASE: mydb
    healthcheck:
      test: mysqladmin ping -u root -p $$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  backend:
    image: backend:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql_data: